### PR TITLE
Build js with typescript

### LINKED ISSUE #2: Set up typescript
Compile backend and frontend code with typescript.

### PR DESCRIPTION
**Pull request by danielj41**
Summary
---

Build client and server js with typescript

Review
---

Direct translations:

https://github.com/danielj41/pulldasher/commit/adbe29c45bf99ada7c2970b281f1b473cea40d5c
https://github.com/danielj41/pulldasher/commit/fb554f86f8f12e649586b4208091689ffa685442?w=1
https://github.com/danielj41/pulldasher/commit/22e7fab04312e09fafab28dc258936024c5a45a1

Actual changes:

https://github.com/danielj41/pulldasher/commit/fbbc3fbd1f4f02afd1c01176eba19656d9135248
https://github.com/danielj41/pulldasher/commit/c9394cf5bd72d17c45aa3b7120104877877452ab
https://github.com/danielj41/pulldasher/pull/1/commits/5d087f16f1b2f0caf9f3bd03773de493ba5d2260

Closes #2

cc @g1y @copperwall

### CODE REVIEW

**Comment by danielj41** [comment]
QA 👍

**Comment by copperwall** [comment]
Oh man I should make my own fork so I can QA my own pulls

**Comment by danielj41** [comment]
test CR 👍

**Comment by danielj41** [comment]
QA 👍

**Comment by danielj41** [comment]
test CR 👍

**Comment by danielj41** [comment]
QA 👍

**Comment by copperwall** [comment]
Dank

**Pull request merged**
